python train_sklearn.py --algorithm RandomForestClassifier --sample_size 0.01 --tune_model false
python train_sklearn.py --algorithm GradientBoostingClassifier --sample_size 0.01 --tune_model false
python train_sklearn.py --algorithm GaussianNB --sample_size 0.01 --tune_model false
python train_sklearn.py --algorithm SVC --sample_size 0.01 --tune_model false
python train_sklearn.py --algorithm RandomForestClassifier --sample_size 0.1 --tune_model false
python train_sklearn.py --algorithm GradientBoostingClassifier --sample_size 0.1 --tune_model false
python train_sklearn.py --algorithm GaussianNB --sample_size 0.1 --tune_model false
python train_sklearn.py --algorithm SVC --sample_size 0.1 --tune_model false
python train_sklearn.py --algorithm RandomForestClassifier --sample_size 1 --tune_model false
python train_sklearn.py --algorithm GradientBoostingClassifier --sample_size 1 --tune_model false
python train_sklearn.py --algorithm GaussianNB --sample_size 1 --tune_model false
python train_sklearn.py --algorithm SVC --sample_size 1 --tune_model false
